// <auto-generated />
using System;
using IPASSData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPASSData.Migrations
{
    [DbContext(typeof(IPassDbContext))]
    [Migration("20241127031159_DB_20241127")]
    partial class DB_20241127
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPASSData.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("NEWID()")
                        .HasComment("使用者 Id");

                    b.Property<string>("Ac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("帳號");

                    b.Property<string>("AuthenticatorUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("驗證器 使用者 Id");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()")
                        .HasComment("創建日期");

                    b.Property<Guid>("CreateBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()")
                        .HasComment("建立者 Id");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("刪除者 Id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("信箱");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("是否刪除");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit")
                        .HasComment("帳號狀態");

                    b.Property<bool>("Is_SuperUser")
                        .HasColumnType("bit")
                        .HasComment("超級使用者");

                    b.Property<DateTime?>("Last_Login")
                        .HasColumnType("datetime2")
                        .HasComment("上次登入時間");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("手機");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("平台來源Id");

                    b.Property<string>("Sw")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("密碼");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()")
                        .HasComment("更新日期");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新者 Id");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("姓名");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
